### PR TITLE
Correct and improve Readme

### PR DESCRIPTION
**Pull request by probins**
Is `setmode` described anywhere? I couldn't find it.

I'd also suggest adding a `depCache` example - this is a very nice feature

### CODE REVIEW

**Comment by guybedford** [comment]
Yes `setmode` has been deprecated for the producton / dev switch actually. The `app/*` meaning `lib/*` paths have been removed to make it simpler to get started and understand (there's enough to explain already!). `setmode` is now just used for the CDN / local switch only. A `depCache` example would be a great idea. If you're interested in updating the PR that would be amazing. Otherwise I'll put some time in to revise when I can.

**Comment by probins** [comment]
so, this demo should be changed to use `lib` rather than `app`? I can do this if you like (close this PR and create a new one).

In more general terms, I would expand/change the demo, as I think it should be a demo of jspm, not es6. jspm can handle both es6 and legacy formats; https2/depCache means you can load modules separately, so jspm is not just about bundling/building; plus you can load existing source from github/npm, so can use jspm server without either es6 or building. Or of course mix these different approaches in one app.

However, saying what I think should be done is the easy bit. :-) I'm around for this week, but am away doing other things for most of March, so probably won't have time to do much in this respect in the near future.

Wandering off-topic a bit, I see that v8 has started work on incorporating basic import/export, so hopefully we will soon have a testbed for using es6 modules without having to load a large transpiler. The demo/docs will have to be changed to reflect this.

**Comment by guybedford** [comment]
@probins yes exactly. I know this demo has aged quite a bit and doesn't cover all the features so well anymore. A PR would be amazing.

No rush at all - if and when you have time - the way open source works!

The initial implementations of ES6 modules will certainly help to raise awareness yes!

**Comment by probins** [comment]
an alternative for demoing depCache would be to link with my app as an example. This works fine, but using an old version of SystemJS. Various things I was doing no longer work with the current loader, so I plan to rewrite and use depCache instead of importing modules separately. However, this will take a while, as I first have to rewrite, make sure depCache works the way I think it does, and also see how HTTP2 push performs with large numbers of modules instead of just a couple of small test files. So don't hold your breath :-) It would though have the advantage of showing people a real app that does something useful in a live environment.

**Comment by guybedford** [comment]
Is there a version you can share in the mean time to see?

Alternatively just making it one of the production steps here as a simple demo and illustrating the ideas can work too.

The issue I have at the moment is I'm trying to maintain a minimal number of projects. That means either keeping this demo really simple, or having someone else owning it with a more fleshed out example.

Happy to go either way here - value your feedback.

**Comment by probins** [comment]
> Is there a version you can share

not really. My current code is a mish-mash of different approaches I've tried with loads of commented-out code, so it wouldn't make a very good training tool. It needs tidying up, refactoring, etc. However, if I can find the time to dedicate to that, it probably wouldn't take too long to do. I've no problem in principle in taking over the demo, but I'm only a part-time developer and have only limited time available.

I'll close this PR, as it's not needed any more. We can open a new issue for improving the demo if you like, and I'll get back to you as and when I have something usable.

**Comment by guybedford** [comment]
Perhaps a first small step would just be to add a simple depCache example then. I've created an issue for that at https://github.com/jspm/demo-es6/issues/12. If and when you have time at any point, it would be great to look at what improvements can be made beyond this to a more interesting demo app.

**Comment by probins** [comment]
I'll base my changes on the new 1.0 loader too, as that seems to be the way forward.

**Comment by guybedford** [comment]
See how it fits with your timeframe - it will be a little while before the alpha is published yet.

**Pull request closed without merging**
